### ISSUE TITLE
What Year Is It?

### ISSUE THREAD

**Issue by eah13** [silshack/spring2016#128]
![](http://e.lvme.me/swtmvsx.jpg)

@tsukori (twice! :))
@jwarrich 
@camazotz 

![screenshot 2016-01-19 at 10 30 15 am](https://cloud.githubusercontent.com/assets/1702745/12423053/aea68cfe-be97-11e5-893b-90abb3144256.png)

**Comment by camazotz** [comment]
@eah13 Just fixed the year

**Comment by tsukori** [comment]
@eah13  fixed the year on my posts as well

**Comment by eah13** [comment]
@camazotz @tsukori awesome!  Will you also make a reference back to this issue from the PR using `#`?  Otherwise it's hard to know what's what.
