### ISSUE TITLE
Missing a first post.

### ISSUE THREAD

**Issue by ColinRNickels** [silshack/spring2016#137]
@wfh1972 I couldn't find a first post for you.
It's probably tied to that directory issue that @eah13 already made an issue for.

**Comment by ColinRNickels** [comment]
I think we fixed it with #144

**Comment by eah13** [comment]
@wfh1972  you can close this issue if it's resolved now.

**Comment by wfh1972** [comment]
Ok to close. We fixed it some time ago.
