### ISSUE TITLE
RhymesWithMecca-Add Spaces Between Post Title Words

### ISSUE THREAD

**Issue by ShyArmadillo8** [silshack/spring2016#146]
@RhymesWithMecca Your first post looks great, but it might be a good idea to put some spaces in your title.

**Comment by RhymesWithMecca** [comment]
@ShyArmadillo8 Fixed it!  Thank you for your wise words of advice!

**Comment by eah13** [comment]
@RhymesWithMecca you can close this issue if it's resolved now.
