### ISSUE TITLE
@jamesma560 .md missing from Ch. 2 Exercise Post

### ISSUE THREAD

**Issue by payalpn** [silshack/spring2016#149]
".md" and the post date were not included in the file name.  Here is a helpful [link](http://silshack.github.io/spring2016/how-to/exercise/githubbasics.html) from the class page to help with naming conventions.  Other than that, the rest of the post is formatted correctly.

**Comment by payalpn** [comment]
@jamesma560 there also seem to be two pull requests for the same post.  #116 and #126 
For future reference, changes can be made to open pull requests (so you don't have to have multiple pull requests open for the same post)

**Comment by eah13** [comment]
@payalpn @jamesma560 tying up loose ends... I think this one was fixed by #116 and/or #126, right?  If so, close this issue

**Comment by jamesma560** [comment]
Yeah I took care of it.
