### ISSUE TITLE
Question re: Assignments

### ISSUE THREAD

**Issue by ericabrody** [silshack/spring2016#166]
@eah13  the "Logical Turtle Exercises" is listed as due at 12am Jan 21, which would be before class. 
Is this item due before class or perhaps at midnight on Jan 21 after class?

Thanks for the clarification
Erica

**Comment by eah13** [comment]
Thanks for posting the question!

This was not a typo, but I betcha most people didn't catch it so I'll treat it like it was.

Most future exercises will be due at midnight before class so I have time to review them before class starts.  I didn't mention this in class so will accept submissions through the beginning of class on this one.
