### ISSUE TITLE
File naming

### ISSUE THREAD

**Issue by eah13** [silshack/spring2016#484]
@wookiemage There are a few posts in your directory that only have one digit for the month.  Jekyll 3 supports this but other versions don't.  It's a small thing, but do a little renaming when you have a moment.

**Comment by ColinRNickels** [comment]
I'll get on this. Thanks for the heads up, @eah13

**Comment by ColinRNickels** [comment]
@eah13 Does the day area need two digits two? Just thought of this after fixing all the others....
:disappointed:

**Comment by eah13** [comment]
Yup. This is the kind of thing to fix half paying attention while watching TV and or drinking a :beer:  

Or at least that's how I'd do it :)

**Comment by ColinRNickels** [comment]
I reopened it so that I would go back through and fix the days as well as the months. There are significantly fewer though. :boom:

**Comment by ColinRNickels** [comment]
I fixed these with my last pull request: #833
