### ISSUE TITLE
File name

### ISSUE THREAD

**Issue by eah13** [silshack/spring2016#487]
@ericabrody @yiyangshi check the filename of the post you submitted together.

**Comment by ericabrody** [comment]
All set now - have (now diagnosed) sinus infection. head hasn't been working well.

**Comment by eah13** [comment]
Great- Could you link to the post or the PR?  It's hard to keep track of what fixes what otherwise.

**Comment by ericabrody** [comment]
This fix is Linked to pull request #510

**Comment by eah13** [comment]
Perfect.  this is ready to be closed!  In the future if you include the magic words "Fixes #487" in you Pull Request, this issue would get closed on merge, saving you some effort.

**Comment by ericabrody** [comment]
Fixes #487
