### ISSUE TITLE
Trinkets not displaying correctly

### ISSUE THREAD

**Issue by tsukori** [silshack/spring2016#530]
So my plan is to create a pull request from our main silshack to my personal fork, updating the messed up posts, and then doing one more pull request with all of those changes from my fork back to the main one. Hopefully this won't break everything.

**Comment by eah13** [comment]
@tsukori this is fixed by #531, so you can close it.  If you include the magic words "Fixes #531" in you PR description it'll do this for you automatically when it gets merged.

**Comment by tsukori** [comment]
Alright, thank you so much!
