### ISSUE TITLE
Disappearing Milestone Post

### ISSUE THREAD

**Issue by EternalFootman** [silshack/spring2016#627]
@eah13  @jamesma560 

I thought that I merged James' post, but it seems to have disappeared entirely. Help?

**Comment by eah13** [comment]
@EternalFootman @jamesma560 is this still a problem?  If so, find the actual file you merged and look for various errors that would confuse Jekyll.  missing .md, improper date format, etc.

**Comment by jamesma560** [comment]
No, this problem was fixed in pull request #664 which I believe you merged. It's also visible on the class website.
