### ISSUE TITLE
Partner switch

### ISSUE THREAD

**Issue by eah13** [silshack/spring2016#679]
@wfh1972 and @camazotz: I'm reassigning you to do each other's peer reviews since your apps are both late.  Please submit your apps ASAP and we'll go from there.  I'll update the assignment with this info soon.

**Comment by camazotz** [comment]
@eah13 I had my app completed and committed on time; I had just forgotten to create a pull request for it. Sorry for the confusion.

**Comment by eah13** [comment]
Got it. The partner switch stands regardless. Where's your PR? That needs to be merged ASAP.
