### ISSUE TITLE
Navaneet's author metadata missing

### ISSUE THREAD

**Issue by eah13** [silshack/spring2016#82]
@camazotz your author name isn't showing up because I never got your [Welcome form](http://silshack.github.io/spring2016/announcement/welcome.html).  Fill that out when you get a chance and @mention me so I can update our config with your name.

I also didn't see you in ConnectCarolina as of the AM.  [email me](mailto:eah13@email.unc.edu) if you need help with any of the above.

**Comment by camazotz** [comment]
@eah13  I just submitted the Welcome form. I also checked ConnectCarolina and it says I am enrolled...not sure why it isn't showing that on your end.

**Comment by eah13** [comment]
You're good to go now.  Thanks!
