### ISSUE TITLE
HuilinLu's author metadata missing

### ISSUE THREAD

**Issue by eah13** [silshack/spring2016#83]
@HuilinLu your author name isn't showing up because I never got your [Welcome form](http://silshack.github.io/spring2016/announcement/welcome.html).  Fill that out when you get a chance and @mention me so I can update our config with your name.

I also didn't see you in ConnectCarolina as of the AM.  If you registered later in the day, no action needed. [email me](mailto:eah13@email.unc.edu) if you need help with any of the above.

**Comment by HuilinLu** [comment]
@eah13 I have just filled out my Welcome Form. Sorry for that I did not register on ConnectCarolina, I think that this course is fantastic!
 Can I audit your class this semester because my class schedule is full?

**Comment by eah13** [comment]
@HuilinLu no, unfortunately.  I'd love to have you in the class but all students need to be enrolled and complete every assignment for my course design to work as intended.  I may teach the same class next Spring, so if it doesn't work out this semester you'll probably have another chance.  

If you do decide to register during this coming week I think it's still possible via a paper form.

You'll of course be able to see and complete the exercises and readings on your own since everything's open on the website.  I hope you do, regardless!

**Comment by HuilinLu** [comment]
@eah13 That's OK, I think I will enroll the same class next Spring!
