### ISSUE TITLE
wfh1972 directory & author name

### ISSUE THREAD

**Issue by eah13** [silshack/spring2016#84]
@wfh1972 take a look at your post.  Your author name isn't displaying in the page because [the author is listed as `WayneHoman`](https://github.com/silshack/spring2016/blame/gh-pages/_posts/WayneHoman/2016-01-12-Homan-Wayne-post.md#L3) but your github username (which is how I've set Jekyll up to recognixe you) is `wfh1972`.    Change the `author:` to be your github username for this and any future posts and your name should show up.

When you change the directory name, just keep backspacing once the filename is empty and you'll be able to rename the directory too:
![screenshot 2016-01-14 at 8 20 51 pm](https://cloud.githubusercontent.com/assets/1702745/12342841/5b302cae-bafc-11e5-903f-96dd7ddb3b18.png)

Feel free to shoot me questions by responding to this issue.

**Comment by ColinRNickels** [comment]
#144 Should fix this issue and create / merge this into the wfh1972 directory

**Comment by wfh1972** [comment]
#144  closed
